## how to handle devices with multiple buttons? 
topics:
  # sonoffs
  tele/son_tv/LWT:
    origin: son_tv
    timeout: 300
    tags:
      - sonoff
  # tele/son_pow_dishwasher/LWT:
  #   origin: son_pow_dishwasher
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_bedroom_lamp/LWT:
  #   origin: son_bedroom_lamp
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_bedrom_led/LWT:
  #   origin: son_bedrom_led
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_kitchen_led/LWT:
  #   origin: son_kitchen_led
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_bedroom_fan/LWT:
  #   origin: son_bedroom_fan
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_lr_fan/LWT:
  #   origin: son_lr_fan
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_pow_lounge/LWT:
  #   origin: son_pow_lounge
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_black_lamp/LWT:
  #   origin: son_black_lamp
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_office_lamp/LWT:
  #   origin: son_office_lamp
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_laundry_lamp/LWT:
  #   origin: son_laundry_lamp
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_lr_table_lamp/LWT:
  #   origin: son_lr_table_lamp
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_lounge_lamp/LWT:
  #   origin: son_lounge_lamp
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_toilet_bulb/LWT:
  #   origin: son_lounge_lamp
  #   timeout: 300
  #   tags:
  #     - sonoff
  # tele/son_th_outside/LWT:
  #   origin: son_th_outside
  #   timeout: 300
  #   tags:
  #     - sonoff


  # Motion Sensors


  
  home/gw/433toMQTT:
    type: json
    attribute: value
    listeners:
      - value: 2678906
        heartbeat:
          origin: mtn-living-room
          timeout: 604800
          tags: 
            - motion_living_room
      - value: 2011696976
        heartbeat:
          origin: rc-1-on
          timeout: 10
          tags: 
            - remote
    heartbeat_global:
      timeout: 300
      origin: "RF Gateway"


  # home/alarm:
  #   origin: Alarm System
  #   attributes:
  #     group: service
  # test:
  #   tags:
  #     - test
  #   attributes:
  #     severity: low
